version: '3'
services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - '8080:5001'
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/memslate
    depends_on:
      db:
        condition: service_healthy 
      libretranslate:
        condition: service_healthy 
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=memslate
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5      
  libretranslate:
    build: 
      context: libretranslate
      args: 
        with_models: 'true'
        models: 'en,ar,ca,zh,nl,fr,de,he,hi,id,it,ja,ko,pl,pt,ru,es,sv,tr,uk,sk'
    container_name: libretranslate
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', './venv/bin/python scripts/healthcheck.py']
    ports:
      - '5000:5000'
    volumes:
      - libretranslate-local:/home/libretranslate/.local
volumes:
  db:
    driver: local
  libretranslate-local:
    driver: local
  
