version: '3'
services:
  web:
    build: .
    ports:
      - '80:5001'
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/memslate
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=memslate
    volumes:
      - db:/var/lib/postgresql/data
  libretranslate:
    image: libretranslate/libretranslate
    ports:
      - '5000:5000'
volumes:
  db:
    driver: local